CREATE DATABASE rootdb;
\c rootdb;

CREATE USER root WITH PASSWORD 'root';
GRANT ALL PRIVILEGES ON DATABASE rootdb TO root;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO root;

CREATE TABLE IF NOT EXISTS public.students (
    id          INT             GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME        VARCHAR(255)    NOT NULL,
    COURSE      VARCHAR(255)    NOT NULL
);

CREATE TABLE IF NOT EXISTS public.emails (
    ID      INT            GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email   varchar(255)    NOT NULL UNIQUE,
    STUDENT_ID    INT    REFERENCES STUDENTS(ID)
);

INSERT INTO STUDENTS (NAME,COURSE) VALUES ('AAAA',1);
INSERT INTO STUDENTS (NAME,COURSE) VALUES ('bbbb',2);
INSERT INTO STUDENTS (NAME,COURSE) VALUES ('CCCC',1);

INSERT INTO EMAILS (EMAIL,STUDENT_ID) VALUES ('AAAA@YANDEX.RU',1);
INSERT INTO EMAILS (EMAIL,STUDENT_ID) VALUES ('bbbb@YANDEX.RU',2);
INSERT INTO EMAILS (EMAIL,STUDENT_ID) VALUES ('CCCCC@YANDEX.RU',3);
INSERT INTO EMAILS (EMAIL,STUDENT_ID) VALUES ('AAAAA@YANDEX.RU',1);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO root;
